# Numpy

#### Documentation:

In [24]:
#For full documentation
website = "https://numpy.org/"
import webbrowser
webbrowser.open(website)

True

## Creatinng Arrays

1. Import the numpy library and check its version.

In [3]:
import numpy as np

## Arrays from lists
### 1-D Array 

2. Given the following **list1** create a numpy array and print it.
* Check the type of the array
* Check the type of the elements inside the array

In [5]:
list1 = [15,20,35,30,35]

In [6]:
array1= np.array(list1)

In [7]:
type(array1)

numpy.ndarray

In [8]:
array1.dtype

dtype('int32')

5. Use **list1** and create an array of float elements, than check the type.

In [11]:
array2 = np.array(list1, dtype='float')

In [12]:
type(array2)

numpy.ndarray

### 2-D array using lists

6. Combine **list1** and **list2** and create a 2-D array. 

In [14]:
list2 = [10,20,30,40]

In [16]:
multy_lists = [list1, list2]
array3 = np.array(multy_lists)

7. Check the shape of your 2-D array.

In [18]:
array3.shape

(2,)

## The .arange() method

#### 1-D array

8. Use the **arange** method and create a 1-D array of 15 elements.  

In [21]:
array4 = np.arange(1,16)
array4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

9. Use the **arange** method and create a 1-D array, start=20, stop=60, steps=2

In [23]:
array5 = np.arange(20,60,2)
array5

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

#### 2-D array, the reshape method

10. Use the **arange** and **reshape** methods. Create an array of 20 elements and shape it 5x4. 

In [26]:
array6 = np.arange(0,20).reshape(5,4)
array6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### 3-D array

11. Use the **arange** and **reshape** methods. Create an array of 40 elements and shape it 2x5x4.

In [29]:
array7 = np.arange(0,40).reshape(2,5,4)
array7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

## Linespace method

12. Use the **linespace** method and create a 1-D array from 0 to 1 with 10 elements inside.

## The randoms methods

13. Use the **random.rand** method and create an array of 15 elements random sampled from a uniform distribution over [0, 1).



In [36]:
np.linspace(0, 15, 100)

array([ 0.        ,  0.15151515,  0.3030303 ,  0.45454545,  0.60606061,
        0.75757576,  0.90909091,  1.06060606,  1.21212121,  1.36363636,
        1.51515152,  1.66666667,  1.81818182,  1.96969697,  2.12121212,
        2.27272727,  2.42424242,  2.57575758,  2.72727273,  2.87878788,
        3.03030303,  3.18181818,  3.33333333,  3.48484848,  3.63636364,
        3.78787879,  3.93939394,  4.09090909,  4.24242424,  4.39393939,
        4.54545455,  4.6969697 ,  4.84848485,  5.        ,  5.15151515,
        5.3030303 ,  5.45454545,  5.60606061,  5.75757576,  5.90909091,
        6.06060606,  6.21212121,  6.36363636,  6.51515152,  6.66666667,
        6.81818182,  6.96969697,  7.12121212,  7.27272727,  7.42424242,
        7.57575758,  7.72727273,  7.87878788,  8.03030303,  8.18181818,
        8.33333333,  8.48484848,  8.63636364,  8.78787879,  8.93939394,
        9.09090909,  9.24242424,  9.39393939,  9.54545455,  9.6969697 ,
        9.84848485, 10.        , 10.15151515, 10.3030303 , 10.45

#### random.randn()

14. Create a 1-D array with 20 elements sampled from the “standard normal” distribution.

In [30]:
np.random.rand(20)

array([0.34560111, 0.1799831 , 0.67588391, 0.65538606, 0.73334534,
       0.32554687, 0.08302743, 0.10757903, 0.9981152 , 0.89606005,
       0.8945333 , 0.50675349, 0.23512156, 0.223904  , 0.27398793,
       0.82716426, 0.39558437, 0.9374175 , 0.5173071 , 0.45911   ])

### Special cases arrays

15. Create a 2-D array of zeros 4x4.

In [32]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

16. Createe a 2-D array of ones 3x3.

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

17. Use the **eye** method and create an array 4x4

In [38]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Congratulation! You completed all the exercises!